#!/bin/bash

# -*- mode: bash; tab-width: 4; indent-tabs-mode: nil -*-

function easy2-authorize-ssh-key() {

    local user="$1"
    local ssh_key="$2"

    local ssh_dir="$(eval echo ~$user)/.ssh"
    local authorized_keys="$ssh_dir/authorized_keys"

    if ! grep -s -q "$ssh_key" "$authorized_keys"; then
        mkdir -p -m 0700 "$ssh_dir"

        echo "$ssh_key" >> "$authorized_keys"
        chmod 0600 "$authorized_keys"

        chown -R "$user":"$(id -gn $user)" "$ssh_dir"

        easy2-info "appended public key to $authorized_keys"
    fi

}

function easy2-ssh-key() {

    local ssh_users="$1"

    local ssh_key="$(easy2-instance-meta public-keys/0/openssh-key 2> /dev/null)" 

    if [ $? -ne 0 ]; then
        easy2-error "could not fetch public key"
        return 1
    fi

    for user in $ssh_users; do

        id "$user" > /dev/null 2>&1

        if [ $? -ne 0 ]; then
            easy2-error "user $user does not exist, skipping"
            continue
        fi

        easy2-authorize-ssh-key "$user" "$ssh_key"

    done

}

easy2-ssh-key "$SSH_USERS"